name: DevSecOps Pipeline – AUY1105

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analisis:
    name: 'Seguridad, Estatico y Politicas'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.0'

      # 1. Analisis Estatico con TFLint
      - name: Instalar TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3
      - name: Ejecutar TFLint
        run: |
          tflint --init
          tflint --recursive

      # 2. Analisis de Seguridad con Checkov
      - name: Ejecutar Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          soft_fail: true 

      # 3. Instalacion de OPA
      - name: Instalar OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/

      # 4. Generacion de Plan y Validacion de Politicas (OPA)
      - name: Terraform Plan & OPA Check
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: 'us-east-1'
        run: |
          terraform init
          # Generamos el plan y lo convertimos a JSON para OPA
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json
          
          echo "Ejecutando politicas OPA..."
          # Evaluamos ambas politicas. Si hay una 'violation', el comando fallará.
          opa exec --decision terraform/ec2/violation --bundle policy/ tfplan.json
          opa exec --decision terraform/ssh/violation --bundle policy/ tfplan.json

  deploy:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    needs: analisis
    # Solo despliega si es un push a la rama main (no en PR)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-east-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve